version: '3.9'

services:
  db:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: tyl_drf_db:dev
    restart: unless-stopped
    container_name: tyl_drf_postgres_dev
    volumes:
      - tyl_drf_postgres_dev:/var/lib/postgresql/data
    env_file:
      - ./postgres/.env.dev
  web_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tyl_drf_web_api:dev
    container_name: tyl_drf_web_api_dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
      - ./postgres/.env.dev
    depends_on:
      - db

volumes:
  tyl_drf_postgres_dev: