version: '3.9'

services:
  db:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: tyl_drf_db:prod
    restart: always
    container_name: tyl_drf_postgres_prod
    volumes:
      - tyl_drf_postgres_prod:/var/lib/postgresql/data
      - logs:/logs
    env_file:
      - ./postgres/.env.prod
  web_api:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: tyl_drf_web_api:prod
    container_name: tyl_drf_web_api_prod
    entrypoint: /usr/src/app/wait-for-postgres.sh
    command: gunicorn test_your_language.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - logs:/usr/src/app/logs
      - static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
      - ./postgres/.env.prod
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: tyl_nginx:prod
    container_name: nginx_prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - logs:/var/www/example.com/logs
      - static:/var/www/example.com/static
    depends_on:
      - web_api

volumes:
  logs:
  static:
  tyl_drf_postgres_prod: